services:
  postgres:
    image: postgres:16-alpine
    container_name: boardgames_its_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: boardgames
      POSTGRES_PASSWORD: boardgames
      POSTGRES_DB: boardgames_its_dev
    ports:
      - '55432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U boardgames -d boardgames_its_dev']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
